### ISSUE TITLE
observable.doAction( ".preventDefault" ) is not working n v3.0

### ISSUE THREAD

**Issue by hirofumii** [baconjs/bacon.js#747]
Hi.
After updating Bacon.js to 3.0, the following code now returns an error.

```js
$( “.foo” ) .doAction( ".preventDefault" ) // TypeError: f is not a function
```

Looks like the doAction argument doesn't accept anything other than a function.

If this is a bug, not a specification change, I'm glad if a fix is considered.
Thanks.

**Comment by raimohanska** [comment]
It's a feature indeed. The string shortcuts are gone in version 3. They are not as useful as they used to be, with modern ES6 or Typescript.

**Comment by raimohanska** [comment]
Would make sense though to include migration instructions in README documentation...
